name: build and publish

on:
  push:
    tags:
      - "v*.*.*"

  pull_request:
    branches: [main, master]

jobs:
  build-pypackage:
    uses: actions/workflows/.gitea/workflows/release_pypackage_github.yml@master
    with:
      repository: main
    secrets:
      username: __token__
      token: ${{ secrets.PACKAGE_TOKEN }}
      gh-token: ${{ secrets.GH_TOKEN }}

  update-changelog:
    uses: actions/workflows/.gitea/workflows/update_changelog.yml@master
    with:
      branch: main
