name: check code

on:
  push:
    branches: [main, master, dev]

  pull_request:
    branches: [main, master, dev]

jobs:
  check-code:
    uses: actions/workflows/.gitea/workflows/check_python_hatch.yml@master
    with:
      run-tests: true
