name: check/lint python code with hatch

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  check-python-hatch:
    runs-on: python311
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install hatch
        run: pip install -U hatch

      - name: test codestyle
        run: hatch run lint:style

      - name: test typing
        run: hatch run lint:typing
